// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: umsg.proto

#ifndef PROTOBUF_umsg_2eproto__INCLUDED
#define PROTOBUF_umsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_umsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsVCF_msg_ExtendedImpl();
void InitDefaultsVCF_msg_Extended();
void InitDefaultsVCF_msgImpl();
void InitDefaultsVCF_msg();
inline void InitDefaults() {
  InitDefaultsVCF_msg_Extended();
  InitDefaultsVCF_msg();
}
}  // namespace protobuf_umsg_2eproto
namespace vcf {
class VCF_msg;
class VCF_msgDefaultTypeInternal;
extern VCF_msgDefaultTypeInternal _VCF_msg_default_instance_;
class VCF_msg_Extended;
class VCF_msg_ExtendedDefaultTypeInternal;
extern VCF_msg_ExtendedDefaultTypeInternal _VCF_msg_Extended_default_instance_;
}  // namespace vcf
namespace vcf {

// ===================================================================

class VCF_msg_Extended : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.VCF_msg.Extended) */ {
 public:
  VCF_msg_Extended();
  virtual ~VCF_msg_Extended();

  VCF_msg_Extended(const VCF_msg_Extended& from);

  inline VCF_msg_Extended& operator=(const VCF_msg_Extended& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VCF_msg_Extended(VCF_msg_Extended&& from) noexcept
    : VCF_msg_Extended() {
    *this = ::std::move(from);
  }

  inline VCF_msg_Extended& operator=(VCF_msg_Extended&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VCF_msg_Extended& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VCF_msg_Extended* internal_default_instance() {
    return reinterpret_cast<const VCF_msg_Extended*>(
               &_VCF_msg_Extended_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(VCF_msg_Extended* other);
  friend void swap(VCF_msg_Extended& a, VCF_msg_Extended& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VCF_msg_Extended* New() const PROTOBUF_FINAL { return New(NULL); }

  VCF_msg_Extended* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VCF_msg_Extended& from);
  void MergeFrom(const VCF_msg_Extended& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VCF_msg_Extended* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 _type = 1;
  void clear__type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::uint32 _type() const;
  void set__type(::google::protobuf::uint32 value);

  // int32 _min = 2;
  void clear__min();
  static const int kMinFieldNumber = 2;
  ::google::protobuf::int32 _min() const;
  void set__min(::google::protobuf::int32 value);

  // int32 _max = 3;
  void clear__max();
  static const int kMaxFieldNumber = 3;
  ::google::protobuf::int32 _max() const;
  void set__max(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:vcf.VCF_msg.Extended)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _type_;
  ::google::protobuf::int32 _min_;
  ::google::protobuf::int32 _max_;
  mutable int _cached_size_;
  friend struct ::protobuf_umsg_2eproto::TableStruct;
  friend void ::protobuf_umsg_2eproto::InitDefaultsVCF_msg_ExtendedImpl();
};
// -------------------------------------------------------------------

class VCF_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vcf.VCF_msg) */ {
 public:
  VCF_msg();
  virtual ~VCF_msg();

  VCF_msg(const VCF_msg& from);

  inline VCF_msg& operator=(const VCF_msg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VCF_msg(VCF_msg&& from) noexcept
    : VCF_msg() {
    *this = ::std::move(from);
  }

  inline VCF_msg& operator=(VCF_msg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VCF_msg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VCF_msg* internal_default_instance() {
    return reinterpret_cast<const VCF_msg*>(
               &_VCF_msg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(VCF_msg* other);
  friend void swap(VCF_msg& a, VCF_msg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VCF_msg* New() const PROTOBUF_FINAL { return New(NULL); }

  VCF_msg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VCF_msg& from);
  void MergeFrom(const VCF_msg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VCF_msg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef VCF_msg_Extended Extended;

  // accessors -------------------------------------------------------

  // repeated .vcf.VCF_msg.Extended ext = 9;
  int ext_size() const;
  void clear_ext();
  static const int kExtFieldNumber = 9;
  const ::vcf::VCF_msg_Extended& ext(int index) const;
  ::vcf::VCF_msg_Extended* mutable_ext(int index);
  ::vcf::VCF_msg_Extended* add_ext();
  ::google::protobuf::RepeatedPtrField< ::vcf::VCF_msg_Extended >*
      mutable_ext();
  const ::google::protobuf::RepeatedPtrField< ::vcf::VCF_msg_Extended >&
      ext() const;

  // string _response = 3;
  void clear__response();
  static const int kResponseFieldNumber = 3;
  const ::std::string& _response() const;
  void set__response(const ::std::string& value);
  #if LANG_CXX11
  void set__response(::std::string&& value);
  #endif
  void set__response(const char* value);
  void set__response(const char* value, size_t size);
  ::std::string* mutable__response();
  ::std::string* release__response();
  void set_allocated__response(::std::string* _response);

  // string _name = 5;
  void clear__name();
  static const int kNameFieldNumber = 5;
  const ::std::string& _name() const;
  void set__name(const ::std::string& value);
  #if LANG_CXX11
  void set__name(::std::string&& value);
  #endif
  void set__name(const char* value);
  void set__name(const char* value, size_t size);
  ::std::string* mutable__name();
  ::std::string* release__name();
  void set_allocated__name(::std::string* _name);

  // uint32 _seqNo = 1;
  void clear__seqno();
  static const int kSeqNoFieldNumber = 1;
  ::google::protobuf::uint32 _seqno() const;
  void set__seqno(::google::protobuf::uint32 value);

  // int32 _result = 2;
  void clear__result();
  static const int kResultFieldNumber = 2;
  ::google::protobuf::int32 _result() const;
  void set__result(::google::protobuf::int32 value);

  // uint32 _owner = 4;
  void clear__owner();
  static const int kOwnerFieldNumber = 4;
  ::google::protobuf::uint32 _owner() const;
  void set__owner(::google::protobuf::uint32 value);

  // uint32 _c_ID = 6;
  void clear__c_id();
  static const int kCIDFieldNumber = 6;
  ::google::protobuf::uint32 _c_id() const;
  void set__c_id(::google::protobuf::uint32 value);

  // uint32 _p_ID = 7;
  void clear__p_id();
  static const int kPIDFieldNumber = 7;
  ::google::protobuf::uint32 _p_id() const;
  void set__p_id(::google::protobuf::uint32 value);

  // int32 _value = 8;
  void clear__value();
  static const int kValueFieldNumber = 8;
  ::google::protobuf::int32 _value() const;
  void set__value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:vcf.VCF_msg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::vcf::VCF_msg_Extended > ext_;
  ::google::protobuf::internal::ArenaStringPtr _response_;
  ::google::protobuf::internal::ArenaStringPtr _name_;
  ::google::protobuf::uint32 _seqno_;
  ::google::protobuf::int32 _result_;
  ::google::protobuf::uint32 _owner_;
  ::google::protobuf::uint32 _c_id_;
  ::google::protobuf::uint32 _p_id_;
  ::google::protobuf::int32 _value_;
  mutable int _cached_size_;
  friend struct ::protobuf_umsg_2eproto::TableStruct;
  friend void ::protobuf_umsg_2eproto::InitDefaultsVCF_msgImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VCF_msg_Extended

// uint32 _type = 1;
inline void VCF_msg_Extended::clear__type() {
  _type_ = 0u;
}
inline ::google::protobuf::uint32 VCF_msg_Extended::_type() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg.Extended._type)
  return _type_;
}
inline void VCF_msg_Extended::set__type(::google::protobuf::uint32 value) {
  
  _type_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg.Extended._type)
}

// int32 _min = 2;
inline void VCF_msg_Extended::clear__min() {
  _min_ = 0;
}
inline ::google::protobuf::int32 VCF_msg_Extended::_min() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg.Extended._min)
  return _min_;
}
inline void VCF_msg_Extended::set__min(::google::protobuf::int32 value) {
  
  _min_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg.Extended._min)
}

// int32 _max = 3;
inline void VCF_msg_Extended::clear__max() {
  _max_ = 0;
}
inline ::google::protobuf::int32 VCF_msg_Extended::_max() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg.Extended._max)
  return _max_;
}
inline void VCF_msg_Extended::set__max(::google::protobuf::int32 value) {
  
  _max_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg.Extended._max)
}

// -------------------------------------------------------------------

// VCF_msg

// uint32 _seqNo = 1;
inline void VCF_msg::clear__seqno() {
  _seqno_ = 0u;
}
inline ::google::protobuf::uint32 VCF_msg::_seqno() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._seqNo)
  return _seqno_;
}
inline void VCF_msg::set__seqno(::google::protobuf::uint32 value) {
  
  _seqno_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._seqNo)
}

// int32 _result = 2;
inline void VCF_msg::clear__result() {
  _result_ = 0;
}
inline ::google::protobuf::int32 VCF_msg::_result() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._result)
  return _result_;
}
inline void VCF_msg::set__result(::google::protobuf::int32 value) {
  
  _result_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._result)
}

// string _response = 3;
inline void VCF_msg::clear__response() {
  _response_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VCF_msg::_response() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._response)
  return _response_.GetNoArena();
}
inline void VCF_msg::set__response(const ::std::string& value) {
  
  _response_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._response)
}
#if LANG_CXX11
inline void VCF_msg::set__response(::std::string&& value) {
  
  _response_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:vcf.VCF_msg._response)
}
#endif
inline void VCF_msg::set__response(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  _response_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:vcf.VCF_msg._response)
}
inline void VCF_msg::set__response(const char* value, size_t size) {
  
  _response_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:vcf.VCF_msg._response)
}
inline ::std::string* VCF_msg::mutable__response() {
  
  // @@protoc_insertion_point(field_mutable:vcf.VCF_msg._response)
  return _response_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VCF_msg::release__response() {
  // @@protoc_insertion_point(field_release:vcf.VCF_msg._response)
  
  return _response_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VCF_msg::set_allocated__response(::std::string* _response) {
  if (_response != NULL) {
    
  } else {
    
  }
  _response_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _response);
  // @@protoc_insertion_point(field_set_allocated:vcf.VCF_msg._response)
}

// uint32 _owner = 4;
inline void VCF_msg::clear__owner() {
  _owner_ = 0u;
}
inline ::google::protobuf::uint32 VCF_msg::_owner() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._owner)
  return _owner_;
}
inline void VCF_msg::set__owner(::google::protobuf::uint32 value) {
  
  _owner_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._owner)
}

// string _name = 5;
inline void VCF_msg::clear__name() {
  _name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VCF_msg::_name() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._name)
  return _name_.GetNoArena();
}
inline void VCF_msg::set__name(const ::std::string& value) {
  
  _name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._name)
}
#if LANG_CXX11
inline void VCF_msg::set__name(::std::string&& value) {
  
  _name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:vcf.VCF_msg._name)
}
#endif
inline void VCF_msg::set__name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  _name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:vcf.VCF_msg._name)
}
inline void VCF_msg::set__name(const char* value, size_t size) {
  
  _name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:vcf.VCF_msg._name)
}
inline ::std::string* VCF_msg::mutable__name() {
  
  // @@protoc_insertion_point(field_mutable:vcf.VCF_msg._name)
  return _name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VCF_msg::release__name() {
  // @@protoc_insertion_point(field_release:vcf.VCF_msg._name)
  
  return _name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VCF_msg::set_allocated__name(::std::string* _name) {
  if (_name != NULL) {
    
  } else {
    
  }
  _name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _name);
  // @@protoc_insertion_point(field_set_allocated:vcf.VCF_msg._name)
}

// uint32 _c_ID = 6;
inline void VCF_msg::clear__c_id() {
  _c_id_ = 0u;
}
inline ::google::protobuf::uint32 VCF_msg::_c_id() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._c_ID)
  return _c_id_;
}
inline void VCF_msg::set__c_id(::google::protobuf::uint32 value) {
  
  _c_id_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._c_ID)
}

// uint32 _p_ID = 7;
inline void VCF_msg::clear__p_id() {
  _p_id_ = 0u;
}
inline ::google::protobuf::uint32 VCF_msg::_p_id() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._p_ID)
  return _p_id_;
}
inline void VCF_msg::set__p_id(::google::protobuf::uint32 value) {
  
  _p_id_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._p_ID)
}

// int32 _value = 8;
inline void VCF_msg::clear__value() {
  _value_ = 0;
}
inline ::google::protobuf::int32 VCF_msg::_value() const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg._value)
  return _value_;
}
inline void VCF_msg::set__value(::google::protobuf::int32 value) {
  
  _value_ = value;
  // @@protoc_insertion_point(field_set:vcf.VCF_msg._value)
}

// repeated .vcf.VCF_msg.Extended ext = 9;
inline int VCF_msg::ext_size() const {
  return ext_.size();
}
inline void VCF_msg::clear_ext() {
  ext_.Clear();
}
inline const ::vcf::VCF_msg_Extended& VCF_msg::ext(int index) const {
  // @@protoc_insertion_point(field_get:vcf.VCF_msg.ext)
  return ext_.Get(index);
}
inline ::vcf::VCF_msg_Extended* VCF_msg::mutable_ext(int index) {
  // @@protoc_insertion_point(field_mutable:vcf.VCF_msg.ext)
  return ext_.Mutable(index);
}
inline ::vcf::VCF_msg_Extended* VCF_msg::add_ext() {
  // @@protoc_insertion_point(field_add:vcf.VCF_msg.ext)
  return ext_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::vcf::VCF_msg_Extended >*
VCF_msg::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_list:vcf.VCF_msg.ext)
  return &ext_;
}
inline const ::google::protobuf::RepeatedPtrField< ::vcf::VCF_msg_Extended >&
VCF_msg::ext() const {
  // @@protoc_insertion_point(field_list:vcf.VCF_msg.ext)
  return ext_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace vcf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_umsg_2eproto__INCLUDED
